### PR TITLE
Form reset fix

### LINKED ISSUE #71: connector widget: form resets when switching db
if I fill out the form for a new connection:

image

and then switch the db from the dropdown, the form resets. it'll be better if it'd kept the values. note that some forms contain different fields (eg duckdb and sqlite only contain alias and database), so we should only fill out the ones that match

### PR DESCRIPTION
**Pull request by neelasha23**
## Issue number

Closes #71 

## Checklist before requesting a review

- [ ] Performed a self-review of my code
- [ ] Formatted my code with [`pkgmt format`](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#linting-formatting)
- [ ] Added [tests](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#testing) (when necessary).
- [ ] Added [docstring](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#documenting-changes-and-new-features) documentation and update the [changelog](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#changelog) (when needed)

### CODE REVIEW

File: src/widgets/connector.ts [hunk 1]
```diff
@@ -378,17 +378,45 @@ export class ConnectorView extends DOMWidgetView {
 
         const connectionTemplate = this.connectionsTemplates[key];
 
+        const form: { [key: string]: any } = {};
```
Comment (edublancas) [inline src/widgets/connector.ts:381]: please give this a more descriptive name, it's unclear what the purpose of this variable is

File: src/widgets/connector.ts [hunk 2]
```diff
@@ -378,17 +378,45 @@ export class ConnectorView extends DOMWidgetView {
...
+            const id = field.id;
+            const defaultValue = field.hasOwnProperty("default")
+              ? field["default"]
+              : "";
+            const formField = <HTMLSelectElement>this.el.querySelector(`#${id}`);
+            if (formField && formField.value != defaultValue) {
+              form[id] = formField.value;
+            }
+          });
+        }
```
Comment (edublancas) [inline src/widgets/connector.ts:399]: add some comments here, I think you're reading the previous form and storing it?

File: src/widgets/connector.ts [hunk 3]
```diff
@@ -378,17 +378,45 @@ export class ConnectorView extends DOMWidgetView {
...
+
+        sessionStorage.setItem("fieldInputs", JSON.stringify(form));
```
Comment (edublancas) [inline src/widgets/connector.ts:401]: where is this sessionStorage coming from? I guess the variable was already declared because I don't see any new declaration

File: ui-tests/tests/widget.test.ts [hunk 4]
```diff
@@ -179,6 +179,410 @@ ConnectorWidget()`)
...
+   test(`test fields are auto-populated if dropdown selection changes, existing connection
+       present, default DB alias displayed: ${label}`, async ({
+        page,
+      }) => {
+        await createNewNotebook(page);
+
+        await page.notebook.enterCellEditingMode(0);
+        const cell = await page.notebook.getCell(0);
+        await cell?.type(`
+from pathlib import Path
```
Comment (edublancas) [inline ui-tests/tests/widget.test.ts:318]: I'm unsure about this test. why would having a connections.ini change anything? or are you testing that a connection.ini does not change behavior?

File: ui-tests/tests/widget.test.ts [hunk 5]
```diff
@@ -179,6 +179,410 @@ ConnectorWidget()`)
...
+  },
+  { label: "Oracle", connectionName: "default", port: "1521", username: "someuser",
+    password: "somepassword", host: "localhost", database: "somedb",
+  },
+  { label: "MSSQL", connectionName: "default", port: "1433", username: "someuser",
+    password: "somepassword", host: "localhost", database: "somedb",
+  },
+  { label: "Redshift", connectionName: "default", port: "5439", username: "someuser",
+    password: "somepassword", host: "localhost", database: "somedb",
+  },
```
Comment (edublancas) [inline ui-tests/tests/widget.test.ts:246]: across all tests, there's only a handful of values that change (e.g. all of these have the same database name, password, etc). so there's no need to parameterized over all values, just over the ones that change. this will make the code more readable

**Review by edublancas — CHANGES_REQUESTED** [review]
i tested it and it works fine. just some recommendations regarding code and test readability

File: src/widgets/connector.ts (hunk 3 above)
Comment (neelasha23) [reply src/widgets/connector.ts:401]: It's part of the Web storage API: https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API

File: src/widgets/connector.ts (hunk 1 above)
Comment (neelasha23) [reply src/widgets/connector.ts]: [fixed](https://github.com/ploomber/jupysql-plugin/pull/75/files#diff-245ccc293a87304bf06e6d14a672d745b47a2cc1951a41def9f729b25ee669e1R381-R382)

File: src/widgets/connector.ts (hunk 2 above)
Comment (neelasha23) [reply src/widgets/connector.ts]: [fixed](https://github.com/ploomber/jupysql-plugin/pull/75/files#diff-245ccc293a87304bf06e6d14a672d745b47a2cc1951a41def9f729b25ee669e1R387-R390)

File: ui-tests/tests/widget.test.ts (hunk 4 above)
Comment (neelasha23) [reply ui-tests/tests/widget.test.ts:318]: If user doesn't change the default connection alias and changes the dropdown there would be two cases:
1. If some connection does not exist, the alias will be `default`.
2. If some other connection exists, the alias will be DB specific, e.g. `oracle` for Oracle DB.

This case is for the 2nd scenario

File: ui-tests/tests/widget.test.ts (hunk 5 above)
Comment (neelasha23) [reply ui-tests/tests/widget.test.ts]: [Fixed](https://github.com/ploomber/jupysql-plugin/pull/75/commits/05c49f46fff95133e1efae6e0dd1256252317214)

File: ui-tests/tests/widget.test.ts (hunk 4 above)
Comment (edublancas) [reply ui-tests/tests/widget.test.ts:291]: right, i forgot about that scenario!

**Review by edublancas — APPROVED** [review]
